development:
  adapter: postgresql
  database: gjs_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: gjs_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: gjs_production
  pool: 5
  timeout: 5000
